.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplos2.3 - Debug ]----------"
	@cd "Ejemplos2.3" && "$(MAKE)" -f  "Ejemplos2.3.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplos2.3 - Debug ]----------"
	@cd "Ejemplos2.3" && "$(MAKE)" -f  "Ejemplos2.3.mk" clean
